version: "3" 

services:
  orion:
    image: fiware/orion:3.7.0
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    entrypoint: ["sh", "-c", "rm /tmp/contextBroker.pid; /usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -disableFileLog -dbhost mongo"]

  mongo:
    image: mongo:4.4
    command: --nojournal

  accumulator:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: accumulator
    tty: true
    ports:
      - 1028:1028
