version: "3"
services:

  # Orion is the context broker
  orion:
    image: fiware/orion:3.7.0
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    entrypoint: ["sh", "-c", "rm /tmp/contextBroker.pid; /usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -disableFileLog -dbhost mongo-db -logLevel DEBUG -noCache"]

  # Databases - Orion uses Mongo-DB, Cygnus is persisting to Postgres
  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    container_name: mongo-db
    ports:
      - "27017:27017"
    command: --nojournal
    volumes:
      - mongo-db:/data

volumes:
  mongo-db:
